"""Stub router — every §1.6 endpoint registered under its final path.

Each stub raises HTTP ``501 Not Implemented`` with a ``detail`` naming the
session that will own the real implementation. ``GET /healthz`` is deliberately
NOT here — it is implemented in ``app.main`` and is the only non-501 route.

SWAP PROTOCOL
-------------
Downstream sessions do NOT edit this file. They create their own router module
(e.g. ``app/api/routers/auth.py``) and register it *ahead of* ``stubs_router``
in ``app/api/routers/__init__.py``. FastAPI resolves the first matching route,
so a real router included before this one shadows the corresponding stubs. The
stubs remain as the fallback for paths nobody has implemented yet.
"""
from __future__ import annotations

from fastapi import APIRouter, HTTPException, status

stubs_router = APIRouter()


def _not_implemented(owner: str) -> HTTPException:
    return HTTPException(
        status_code=status.HTTP_501_NOT_IMPLEMENTED,
        detail=f"Not implemented — session {owner} owns this endpoint",
    )


def _p1(feature: str) -> HTTPException:
    return HTTPException(
        status_code=status.HTTP_501_NOT_IMPLEMENTED,
        detail=f"Not implemented — P1 endpoint ({feature}); not scheduled in the current build plan",
    )


# ---------------------------------------------------------------------------
# Auth — owned by S2-A
# ---------------------------------------------------------------------------
@stubs_router.post("/auth/register")
def auth_register() -> None:
    raise _not_implemented("S2-A")


@stubs_router.post("/auth/login")
def auth_login() -> None:
    raise _not_implemented("S2-A")


@stubs_router.post("/auth/oauth/google")
def auth_oauth_google() -> None:
    raise _not_implemented("S2-A")


@stubs_router.post("/auth/refresh")
def auth_refresh() -> None:
    raise _not_implemented("S2-A")


@stubs_router.post("/auth/logout")
def auth_logout() -> None:
    raise _not_implemented("S2-A")


@stubs_router.post("/auth/password-reset/request")
def auth_password_reset_request() -> None:
    raise _not_implemented("S2-A")


@stubs_router.post("/auth/password-reset/confirm")
def auth_password_reset_confirm() -> None:
    raise _not_implemented("S2-A")


# ---------------------------------------------------------------------------
# Drawings — owned by S2-B
# ---------------------------------------------------------------------------
@stubs_router.post("/drawings/hash-check")
def drawings_hash_check() -> None:
    raise _not_implemented("S2-B")


@stubs_router.get("/drawings")
def drawings_list() -> None:
    raise _not_implemented("S2-B")


@stubs_router.post("/drawings")
def drawings_create() -> None:
    raise _not_implemented("S2-B")


@stubs_router.get("/drawings/{drawing_id}")
def drawings_get(drawing_id: str) -> None:
    raise _not_implemented("S2-B")


@stubs_router.patch("/drawings/{drawing_id}")
def drawings_patch(drawing_id: str) -> None:
    raise _not_implemented("S2-B")


@stubs_router.delete("/drawings/{drawing_id}")
def drawings_delete(drawing_id: str) -> None:
    raise _not_implemented("S2-B")


@stubs_router.post("/drawings/{drawing_id}/retry")
def drawings_retry(drawing_id: str) -> None:
    raise _not_implemented("S2-B")


@stubs_router.get("/drawings/{drawing_id}/status")
def drawings_status(drawing_id: str) -> None:
    # SSE stream in the real implementation (S2-B).
    raise _not_implemented("S2-B")


@stubs_router.post("/drawings/{drawing_id}/upload-complete")
def drawings_upload_complete(drawing_id: str) -> None:
    raise _not_implemented("S2-B")


# ---------------------------------------------------------------------------
# Symbols & corrections — owned by S2-C
# ---------------------------------------------------------------------------
@stubs_router.get("/drawings/{drawing_id}/symbols")
def drawings_symbols_list(drawing_id: str) -> None:
    raise _not_implemented("S2-C")


@stubs_router.post("/drawings/{drawing_id}/symbols")
def drawings_symbols_create(drawing_id: str) -> None:
    raise _not_implemented("S2-C")


@stubs_router.patch("/symbols/{symbol_id}")
def symbols_patch(symbol_id: str) -> None:
    raise _not_implemented("S2-C")


# ---------------------------------------------------------------------------
# Exports — owned by S2-D
# ---------------------------------------------------------------------------
@stubs_router.post("/drawings/{drawing_id}/exports")
def drawings_exports_create(drawing_id: str) -> None:
    raise _not_implemented("S2-D")


@stubs_router.get("/exports/{export_id}")
def exports_get(export_id: str) -> None:
    raise _not_implemented("S2-D")


# ---------------------------------------------------------------------------
# Account, consent & GDPR init — owned by S2-F
# ---------------------------------------------------------------------------
@stubs_router.get("/account")
def account_get() -> None:
    raise _not_implemented("S2-F")


@stubs_router.patch("/account")
def account_patch() -> None:
    raise _not_implemented("S2-F")


@stubs_router.delete("/account")
def account_delete() -> None:
    raise _not_implemented("S2-F")


@stubs_router.get("/account/consent")
def account_consent_get() -> None:
    raise _not_implemented("S2-F")


@stubs_router.patch("/account/consent")
def account_consent_patch() -> None:
    raise _not_implemented("S2-F")


# ---------------------------------------------------------------------------
# Subscription & Stripe webhook — owned by S2-E
# ---------------------------------------------------------------------------
@stubs_router.get("/subscription")
def subscription_get() -> None:
    raise _not_implemented("S2-E")


@stubs_router.post("/subscription/checkout")
def subscription_checkout() -> None:
    raise _not_implemented("S2-E")


@stubs_router.post("/webhooks/stripe")
def webhooks_stripe() -> None:
    raise _not_implemented("S2-E")


# ---------------------------------------------------------------------------
# Entity classes — owned by S2-G
# ---------------------------------------------------------------------------
@stubs_router.get("/entity-classes")
def entity_classes() -> None:
    raise _not_implemented("S2-G")


# ---------------------------------------------------------------------------
# P1 endpoints — teams (no Phase-2 owner; deferred to P1)
# ---------------------------------------------------------------------------
@stubs_router.get("/teams")
def teams_list() -> None:
    raise _p1("team workspace")


@stubs_router.post("/teams")
def teams_create() -> None:
    raise _p1("team workspace")


@stubs_router.get("/teams/{team_id}/members")
def teams_members_list(team_id: str) -> None:
    raise _p1("team workspace")


@stubs_router.post("/teams/{team_id}/members")
def teams_members_add(team_id: str) -> None:
    raise _p1("team workspace")


@stubs_router.delete("/teams/{team_id}/members/{user_id}")
def teams_members_remove(team_id: str, user_id: str) -> None:
    raise _p1("team workspace")


@stubs_router.get("/teams/{team_id}/consent")
def teams_consent_get(team_id: str) -> None:
    raise _p1("team workspace")


@stubs_router.patch("/teams/{team_id}/consent")
def teams_consent_patch(team_id: str) -> None:
    raise _p1("team workspace")


# ---------------------------------------------------------------------------
# P1 endpoints — revision comparison
# ---------------------------------------------------------------------------
@stubs_router.post("/drawings/compare")
def drawings_compare() -> None:
    raise _p1("revision comparison")


@stubs_router.get("/comparisons/{comparison_id}")
def comparisons_get(comparison_id: str) -> None:
    raise _p1("revision comparison")


@stubs_router.get("/exports/{export_id}/comparison-csv")
def exports_comparison_csv(export_id: str) -> None:
    raise _p1("revision comparison")


# ---------------------------------------------------------------------------
# P1 endpoints — instrument table extraction
# ---------------------------------------------------------------------------
@stubs_router.get("/drawings/{drawing_id}/tables")
def drawings_tables(drawing_id: str) -> None:
    raise _p1("instrument table extraction")


@stubs_router.patch("/table-cells/{cell_id}")
def table_cells_patch(cell_id: str) -> None:
    raise _p1("instrument table extraction")
